### ISSUE TITLE
Cannot use a 0 length buffer with Condominium (stacked) parcels

### ISSUE THREAD

**Issue by busbus** [Esri/land-use-public-notification#36]
1. Using the try-it-now service (http://tryitlive.arcgis.com/PublicNotification/), locate parcel number 0714222002 using the search.
2. Notify using a 0 length buffer
3. "Parcel not found at current location"

**Comment by LindsayThomas** [comment]
get data from here to test https://geonet.esri.com/message/557650?et=watches.email.thread#557650

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas 
We are able to reproduce this issue. When a zero length buffer is used, the app queries all parcels that are 'contained' by the selected parcel's geometry. Theoretically, the 'contains' operation should return exactly overlapping polygons too. And, we see that this works fine with single (non-stacked) parcels. In theory, the same 'contains' operation should return all stacked parcels, since they are exactly the same geometry (parcels stacked on top of each other).  
This appears to be an issue with ArcGIS Server. 

Please let us know if the above explanation is making sense. 

We also looked at the sample data from skiley in geonet thread and found that it does not follow Local Gov Information Model. We were able to locate a unique identifier field for parcels (PIN) but were not able to locate a field for lowest parcel identifier. Also, we could not find stacked parcels in the data we downloaded for Anoka County.

![image](https://cloud.githubusercontent.com/assets/2959186/10845654/9eeee614-7f2f-11e5-8110-b8f3166ef42f.png)

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam We are going to separate these issues because they may or may not be related. 

Let's focus on the first repo scenario with stacked parcels. 

When you say this is a Server issue, can you provide more technical details. 

Does a CONTAIN operation using 0 not return results in REST or do it happen with the GP Server?

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas 

About the server issue with 'contains' operation here are the steps to reproduce.

**Non-stacked parcel**
1. Get the geometry of a single parcel (0714201003) using this [query](http://tryitlive.arcgis.com/arcgis/rest/services/TaxParcelQueryIL/MapServer/0/query?where=PARCELID%3D%270714201003%27&text=&objectIds=&time=&geometry=&geometryType=esriGeometryPoint&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=&returnGeometry=true&maxAllowableOffset=&geometryPrecision=&outSR=102100&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&f=pjson)
2. Query the same layer by using the same geometry with a *contains* operation. It returns the same parcel. Please execute a query by filling up the following parameters
  * where: 1=1
  * input geometry: {"rings":[[[-9815608.6345023531,5128616.0112211537],[-9815647.6975930631,5128580.266651446],[-9815668.6817259695,5128628.4591113571],[-9815607.0273926929,5128659.3433521939],[-9815604.8999708761,5128657.7838448929],[-9815603.2960191835,5128655.7102287617],[-9815602.7293170989,5128653.1457664119],[-9815603.3058462162,5128650.5702442871],[-9815605.0769406743,5128648.3234217633],[-9815607.1722991373,5128646.1883589234],[-9815608.9946385082,5128643.8182391394],[-9815610.5160384271,5128641.2494374076],[-9815611.7150036655,5128638.5198191088],[-9815612.5728440899,5128635.671152764],[-9815613.0768963918,5128632.7448147088],[-9815613.2203835119,5128629.7854179787],[-9815613.0004130863,5128626.8369106501],[-9815612.4207888208,5128623.9429842215],[-9815611.4900025371,5128621.1466666805],[-9815610.2215034477,5128618.48951656],[-9815608.6345023531,5128616.0112211537]]]}
  * the above geometry is the same that was retrieved from the earlier query in step 1
  * geometry type: polygon
  * input spatial reference: 102100
  * spatial relationship: contains
  * outfields: PARCELID
  * click on query(post)  
  
Observe that the result is parcelid 0714201003, i.e., the same parcel is found containing itself. This is the expected behavior of 'contains' operation. "A polygon contains itself."  

**Stacked parcel**
1. Get the geometry of a stacked parcel (0714201003) using this [query](http://tryitlive.arcgis.com/arcgis/rest/services/TaxParcelQueryIL/MapServer/0/query?where=PARCELID%3D%270714222002%27&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=PARCELID&returnGeometry=true&maxAllowableOffset=&geometryPrecision=&outSR=102100&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&f=pjson)
2. Query the same layer by using the same geometry with a *contains* operation. Please execute a query by filling up the following parameters
  * where: 1=1
  * input geometry: {"rings":[[[-9815874.930639185,5128066.9949367577],[-9815883.8679080885,5128063.7875692463],[-9815892.9528752211,5128061.0261648893],[-9815902.1633024607,5128058.7174830334],[-9815911.4766445812,5128056.8671748545],[-9815911.6819831841,5128056.8319299547],[-9815922.3058978077,5128054.7119620116],[-9815932.7995724529,5128052.0203791205],[-9815943.1322753206,5128048.7650638567],[-9815953.2737460341,5128044.9555497449],[-9815981.9792524949,5128119.4577244893],[-9815951.6693067867,5128131.2296243757],[-9815942.0431549307,5128113.4188615344],[-9815708.8895857893,5128203.9204675844],[-9815684.5956923999,5128140.8737320807],[-9815722.662700776,5128126.0983932354],[-9815760.7299948204,5128111.3225222463],[-9815798.7971713506,5128096.546924809],[-9815836.8636962157,5128081.7707935171],[-9815874.930639185,5128066.9949367577]]]}
  * the above geometry is the same that was retrieved from the earlier query in step 1
  * geometry type: polygon
  * input spatial reference: 102100
  * spatial relationship: contains
  * outfields: PARCELID
  * click on query(post)  

Since there are stacked parcels of exactly the same geometry, you would expect it should return all stacked parcels (there are 22 stacked parcels). However, you'd notice that server returns "No records found." It does not return even the same parcel that "contains itself" as in the case of non-stacked parcel.

**Comment by busbus** [comment]
Under investigation...

**Comment by busbus** [comment]
Still investigating - I cannot seem to make the CONTAINS query to work at all on hosted services...is this a known issue?  Please see if you can reproduce with the following service/queries.

Stacked Parcel:  00461804601500

http://services2.arcgis.com/PWJUSsdoJDp7SgLj/arcgis/rest/services/CommParcels/FeatureServer/0/query


{
        "rings" : 
        [
          [
            [-13595074.8195, 6140588.6546], 
            [-13595066.5201, 6140585.5039], 
            [-13595097.257, 6140586.2784], 
            [-13595096.8038, 6140604.3716], 
            [-13595074.8195, 6140588.6546]
          ]
        ]
}

Single Parcel:  00461804601700

     {
        "rings" : 
        [
          [
            [-13595051.8518, 6140575.9743], 
            [-13595052.4252, 6140553.0889], 
            [-13595098.0594, 6140554.2387], 
            [-13595097.4863, 6140577.1242], 
            [-13595051.8518, 6140575.9743]
          ]
        ]
      }

**Comment by busbus** [comment]
1. Looks like there are inconsistent results with ArcGIS Online hosted feature services as well as ArcGIS Server feature services with 'Contains'.

Hosted services fail to return same-shape polygons, please confirm the above query.

2. As for many-duplicate polygons (condominiums) with a 0 length buffer - I would recommend simply using the returned polygons for the original query using LOWPARCELID and not applying the spatial filter ('Contains').

Chris

**Comment by CTLocalGovTeam** [comment]
@busbus 

That is correct. We too are observing that AGOL hosted features services fail to return same-shape polygons with a 'Contains' query. So our current approach will fail even for non-stacked parcels.

The suggested approach for querying with LOWPARCELID for returning polygons when buffer is set to 0 sounds good. 
We can do this in these two cases when the buffer is set to 0:
* When a single parcel is selected, either by parcelid or address, or click to select
* When multiple parcels are selected using ctrl+click,

**Comment by busbus** [comment]
Fixed with V4.8

**Comment by busbus** [comment]
Tested on Firefox - seems to generate the mailing labels just fine but seems to cause a non-refreshed state when returning to the application.

1. Select the condo parcel in the try-it-live service
![notifycondo](https://cloud.githubusercontent.com/assets/5614261/12096954/b3660bdc-b2cd-11e5-81ae-0096484fa1f2.png)
2. Choose a 0 length buffer
3. Notify property owners and create Avery labels (5160)
4. Close generated PDF - map is left in the following state
![non-refreshed](https://cloud.githubusercontent.com/assets/5614261/12096981/dc332770-b2cd-11e5-9b53-803917711d20.png)

**Comment by CTLocalGovTeam** [comment]
@busbus 

We are not able to reproduce the issue at our end. Here is the demonstration of 0 length buffer functionality in case of condominium parcels.

Tested on Firefox 42 and 43 
![firefox-pn 36](https://cloud.githubusercontent.com/assets/2959186/12113077/8f6d35a8-b3c6-11e5-9c38-eb5318bf6c6c.gif)

Internet Explorer 11 
![ie11-pn 36](https://cloud.githubusercontent.com/assets/2959186/12113076/8f6c8fc2-b3c6-11e5-9b83-d3d09c56b7fa.gif)

Please let us know if we have missed anything

**Comment by busbus** [comment]
Not missing anything - but this is what I'm seeing...any ideas?
![refreshissue](https://cloud.githubusercontent.com/assets/5614261/12157201/fa0af8be-b484-11e5-8920-b0b86bbdee5d.gif)

**Comment by busbus** [comment]
@CTLocalGovTeam it appears to be an issue with my map service - works fine with the try it services.  I need to confirm my settings to make sure that it's not a more serious issue with other services before I close.

**Comment by busbus** [comment]
Fixed with 4.7
