### ISSUE TITLE
Enhancement - Support free-hand drawing of polygon for selecting underlying parcels (polygons)

### ISSUE THREAD

**Issue by ChrisBuscaglia** [Esri/land-use-public-notification#44]
High-level requirements:

- Simple way to draw a polygon shape over the map and select the underlying parcels (polygons).
- Functionality needs to be a configurable option (on/off - ON by default).
- Configure which of the layers get selected when drawing the polygon shape (parcels by default).

The scope of this enhancement includes the following.

1. UI Design, review with Lindsay Thomas & Chris Buscaglia
2. Implementation
3. Testing

**Comment by CTLocalGovTeam** [comment]
@busbus @LindsayThomas 

We see three options to add support for free-hand drawing of polygon. Please let us know which one you'd prefer to implement.

![image](https://cloud.githubusercontent.com/assets/2959186/10905697/f89596c6-8241-11e5-946d-1435aaa50f14.png)

![image](https://cloud.githubusercontent.com/assets/2959186/10905701/093fa0c0-8242-11e5-9a50-67d29c32cdb1.png)

![image](https://cloud.githubusercontent.com/assets/2959186/10905728/347d2c3a-8242-11e5-9682-cc914500d887.png)

**Comment by ScottOppmann** [comment]
@busbus @LindsayThomas - I would probably lean toward option 2 but with some modifications.  I would flip search and draw on the main toolbar.  In addition, we should discuss whether we need the current location button anymore.  I am leaning towards removing it - doubt anyone is using it.  In addition, @CTLocalGovTeam should also describe what the user interaction will look like once the user selects the draw button.  Does it invoke the free-hand drawing tool, polygon drawing tool, or some other experience.

**Comment by CTLocalGovTeam** [comment]
@ScottOppmann @busbus @LindsayThomas 
User will click to activate the tool and draw the polygon as shown in this animated graphic. Cursor tool tips will guide the user to draw the polygon. We were thinking of using polygon drawing tool, not the free-hand. We could do freehand too. 

![drawpolygon](https://cloud.githubusercontent.com/assets/2959186/10908110/422e0760-8255-11e5-9c36-14a73979fc32.gif)

**Comment by busbus** [comment]
@ScottOppmann  I like the idea of separating the search from the draw - so I like option 2, including the removal of the locate button.
@ScottOppmann @LindsayThomas
One thing that we should consider - if you know where the area of interest is, parcel, school district, etc. you may need to get there first before you start drawing - therefore, I like the idea of grouping search and draw...so would the UX be better grouping them within the search?  One less button click/hiccup in the workflow.

**Comment by busbus** [comment]
@CTLocalGovTeam We should keep to the polygon drawing tool - should have used that terminology from the start.  Updated the requirements.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam 
Please use option 2. 
As @busbus confirmed please use the polygon drawing tool

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas @ScottOppmann 

In the current application, app header contains five icons(Search, Geo location, Print, Share and Help). Since we have decided to include “Polygon drawing tool” in the header, the header will now contain six icons.
Here is the screenshot of how it will look before and after adding Polygon drawing tool in Iphone 5.

![image](https://cloud.githubusercontent.com/assets/2959186/11300754/8cb75ff6-8fb7-11e5-9e84-7f2f001f1630.png)

Please let us know if this is ok.

**Comment by ScottOppmann** [comment]
@CTLocalGovTeam - The search widget should be the first, followed by the drawing tool, then the rest of the tools on the current toolbar.

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas,
We had a question about the requirement to make the layer that gets selected (when a polygon is draw), configurable. The workflows in the app are designed to always select parcels to notify. For e.g,
1. click on map to select parcel, show infopopup, enter buffer distance, select parcels to notify
2. select road centerline, show infopopup, enter buffer distance, select parcels to notify

Can you please describe your thoughts about configuring the layer that gets selected when user draws a polygon.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Per discussion, we do not need to make the layer to be selected configurable. It should just be the parcel layer.

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas, @busbus, @ScottOppmann 
Here is a screen video of the draw polygon to notify feature we have developed so far. We wanted to confirm the workflow. The steps are:
1. Activate polygon tool and draw polygon
2. Select parcels 
3. Click any parcel to show info-popup 
4. Click notify
5. Select occupants or owners and either pdf or csv or both and click download

We feel, that the option to provide buffer distance should be removed from popup in this case. Because, the user has already drawn the desired area and selected the parcels to notify. Please confirm.

![animation](https://cloud.githubusercontent.com/assets/2959186/11583824/420b49c2-9a84-11e5-8d8f-c13284a98cfb.gif)

**Comment by ScottOppmann** [comment]
@busbus @LindsayThomas - I think this workflow is pretty straightforward.  The only thing I'd like to see cleaned up is the is the "click" required to invoke the popup and subsequent mailing labels.  Perhaps the popup should be invoked as soon as the user completes drawing the polygon?  Can you see any shortcomings with that approach?

**Comment by CTLocalGovTeam** [comment]
@ScottOppmann, we need the 'click', because the popup is designed to show information about the clicked parcel with an option to notify in popup title bar.

**Comment by busbus** [comment]
@CTLocalGovTeam I agree with @ScottOppmann  - The single parcel popup in this workflow is relatively useless - unless you could get a summary of all parcels selected with the drawing tool.  Even with that being said, not sure how important that would be either.  

I would recommend basically "clicking" programtically and then jump right to the notification window (clearing the header of any parcel info (address by default).

Please also default this method for notification to 0 length buffer - since this is the area to be notified without modification...

**Comment by busbus** [comment]
Please align the new "add adjacent parcel" text in the buffer dialog to the "download" option.

![addadjacent](https://cloud.githubusercontent.com/assets/5614261/12095818/357f654e-b2c6-11e5-90c6-ea7efc5c5b68.png)

**Comment by CTLocalGovTeam** [comment]
@busbus

We’ve updated it to look the way shown here. Let us know if this looks good and we’ll send a new pull request with this change.

![image](https://cloud.githubusercontent.com/assets/2959186/12164452/99f54260-b53b-11e5-9b1d-fb2f9713cbd7.png)

**Comment by busbus** [comment]
Looks good, thanks!

**Comment by CTLocalGovTeam** [comment]
@busbus Yes we can default to use a 0 length buffer when using polygon tool.
