### ISSUE TITLE
Using dynamic map services / feature services as basemaps

### ISSUE THREAD

**Issue by ChrisBuscaglia** [Esri/land-use-public-notification#55]
@CTLocalGovTeam 

Is there a way to use a dynamic map service as a basemap for the app?  I cannot get this to work with non-tiled map services and/or feature services.

```
    BaseMapLayers: [{
        Key: "streetMap",
        ThumbnailSource: "js/library/themes/images/parcelmap.png",
        Name: "Streets",
        MapURL: "http://tryitlive.arcgis.com/arcgis/rest/services/GeneralPurpose/MapServer"
```

A customer would like to use a dynamic map service for the application since there are many parcel splits/combines/mutations that happen often - re-publishing will be time consuming for simple updates.
<span><b>Salesforce ID:</b> ENH-000092877</span><br/>

**Comment by CTLocalGovTeam** [comment]
@busbus 
The app currently supports only tiled map services to use as basemap.

1. We need to handle services of each type separately. We can easily add support for dynamic map services by identifying if the service has a tile cache. If it does not, then we add it as a dynamic map service. URLs need to be configured without any layerids at the end. 

2. Do we need to support feature services too? Because, feature services cannot be added as dynamic map service, they can be added as feature layers only. And only the first 1000 features are downloaded and displayed at the client. So, using a feature layer as a basemap does not sound useful.

3. There are additional types of services which will need handling separately for e.g., OpenStreetMap, ImageService, WMS etc. Please let us know if you'd like to include support for any additional types.

**Note:** When we add support for any service, we need to modify the basemap gallery widget, as well as the Print widget in the app. Because the Print widget, collects all layers from the main app and displays it in a new window to print from. 

From the points above, implementing bullet no.1 is straightforward, bullet no.2 and 3 require significant code changes.

**Comment by busbus** [comment]
Assigned back to Esri for discussion, thanks for answering my question.

**Comment by gdherbert** [comment]
Is this on the development roadmap?

> We can easily add support for dynamic map services by identifying if the service has a tile cache. If it does not, then we add it as a dynamic map service. URLs need to be configured without any layerids at the end.

**Comment by ChrisBuscaglia** [comment]
@gdherbert This is definitely on the roadmap - maybe as early as late this year as we are moving this application to Web AppBuilder for ArcGIS widget and will support feature layers and map services with query capabilities.  

We may not talk specifically about the different basemap and layer types supported, we will talk about the new application in the meetup on 9/21/2017.

https://www.meetup.com/ArcGIS-for-Local-Government/events/242931626/

http://server.arcgis.com/en/server/latest/get-started/windows/tutorial-publishing-a-map-service.htm#ESRI_SECTION1_81E23A8290DB425694024B602CE5B8A6 

@ScottOppmann
