### ISSUE TITLE
Occupant Avery Labels have City ST Zip on separate lines

### ISSUE THREAD

**Issue by JohnsonV** [Esri/land-use-public-notification#74]
After clicking the Download button to have Avery labels for Occupant, the city, state and zip code appear on three separate lines in the labels.  See attached .png file.  I'm using Chrome browser.  Tested this using the app via the "Try the Public Notificaiton" link on github (http://tryitlive.arcgis.com/PublicNotification/) and in the app after installing it on my own server using the Naperville sample data.  Tried choosing Property Owner and Occupant, and the Owner labels are fine (city state zip all on one line) but the Occupant labels are wrong. Need the City, ST and zip on one line to meet postal format.
![occupant_averylabels_notinpostalformat](https://cloud.githubusercontent.com/assets/19615864/15622046/4298a162-241a-11e6-92c8-d71fc414db85.png)

**Comment by MikeTschudi** [comment]
Initial fix in commit a764ef01202c6e10696b00b0226236c722f17684

cf. 
Salesforce ID: BUG-000103133
Salesforce Submitter: Bradley Snider
Salesforce Submit Date: 2/23/2017 11:35 AM
Salesforce Bug Type: Usability
Salesforce Severity: Medium

**Comment by MikeTschudi** [comment]
@ChrisBuscaglia, the proposed solution changes config.js to give a configurer more control over the CSV label. This permits the combination of fields such as city, state, & zip on a single line. Would you please review the proposed solution for configuration usability? I can resume testing after any changes to the design. The solution can be used in the new Public Notification widget as well.

---
Previously, the occupant labels were defined by a single configuration parameter: `OccupantFields`, which was used for both Avery label PDF and CSV output. There was no way to combine city, state, & zip (or any other fields) on a single line or in a single column.

The proposed change adds two new configuration properties: `AveryFieldsOccupantCollection` and `CsvFieldsOccupantCollection`. These are nearly identical in form and behavior to the corresponding properties for controlling owner Avery labels (`AveryFieldsCollection`) and owner CSV tables (`CsvFieldsCollection`) in that fields are listed in an array with each element of the array defining a label line or table column; in addition, fields may be arbitrarily combined on a line or in a column. To combine fields, one combines them separated by commas in the list. For example, the property value
```
["PARCELID", "OWNERNME1", "OWNERNME2", "PSTLADDRESS", "PSTLCITY,PSTLSTATE,PSTLZIP5"]
```
creates a five-line Avery label or five-column CSV table, with the fields `PSTLCITY`, `PSTLSTATE`, and `PSTLZIP5` on the same line/in the same column separated by spaces.

There is one small difference for the occupant properties. In order to give the configurer control over where the `OccupantLabel` property is to appear, a `null` is used as a placeholder. For example, the occupant collection property value
```
["PARCELID", null, "PSTLADDRESS", "PSTLCITY,PSTLSTATE,PSTLZIP5"]
```
puts the value of the `OccupantLabel` property on the second line (Avery) or in the second column (CSV). Note that this approach prevents the value of the `OccupantLabel` property from being combined with fields on the same line/in the same column. If this behavior is desired, we can replace the `null` with a [character that cannot be used in a field name](http://support.esri.com/technical-article/000005588), e.g., "@".

Backwards compatibility is kept: if `OccupantFields` is uncommented and either of the new Occupant properties is not present, `OccupantFields` is split on its commas into an array and is used to set the missing property(ies). The value of the `OccupantLabel` is hard-coded into the second line/column as it is now. Note that backwards compatibility means that city, state, and zip are on separate lines in the label because `OccupantFields` generates a simple list.

**Comment by jschuckert** [comment]
Hi All,

I just recently called tech support and opened a case on this very same issue. Now stumbling across this thread I forwarded them the link.

In addition to the misalignment of State and Zip (getting pushed to the 5th and 6th lines), the occupant fields are incorrect too. For occupants everything should be pointing to situs not postal/mailing. Folks can fairly easily change the field names in the config file, however someone utilizing the LGIM schema might overlook this issue.
-------
//Fields of the occupant
            OccupantFields: "PARCELID,SITEADDRESS,**PSTLCITY,PSTLSTATE,PSTLZIP5**",
-------

Any updates would be greatly appreciated.

**Comment by jschuckert** [comment]
Hi All,

Earlier today I called tech support and opened a case on this very same issue. Now stumbling across this thread I went ahead and forwarded them the link to this.

In addition to the misalignment of state and zip (getting pushed to the 5th and 6th lines), the occupant fields are incorrect as well. For occupants everything should be pointing at situs not postal/mailing. Folks can fairly easily change the referenced fields in the config file, however someone utilizing the LGIM schema could very easily overlook this error as no tweaking of the field names should be required to stand up the app.

------
//Fields of the occupant
            OccupantFields: "PARCELID,SITEADDRESS,PSTLCITY,PSTLSTATE,PSTLZIP5",

------

Any updates regarding both these issues would be greatly appreciated thanks.

**Comment by ChrisBuscaglia** [comment]
@jschuckert We have made a change for the occupant labels here:  https://github.com/Esri/land-use-public-notification/tree/occupant  This includes a change in the config.js file and the application code, we have tested it, but please note that this is a development version and not currently supported by tech support.

**Comment by jschuckert** [comment]
@ChrisBuscaglia  Understood thanks. 

Just tested and it works great. I really like that new flexibility to be able to specify each field as it's own line or column. I went a head and split City State and Zip into individual columns for the csv output only.

Just so I have a sense for implementing this beyond our test environment, what is the timing of rolling this updated version out to production and having full technical support?
